[package]
name = "popfeedback"
version = "0.1.0"
edition = "2021"

[lib]
name = "popfeedback"
path = "src/lib.rs"

#[[bin]]
#name = "popfeedback"
#path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
